name: Push/PR

on:
  push:


jobs:
  static-analysis:
    name: Run all static analysis checks
    runs-on: ubuntu-22.04
    steps:
      - name: Download zip from GH Release assets and extract .exe
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: v2.10.3
        run: |
          gh release download v2.10.3 --pattern nri-mssql-amd64.${TAG#v}.zip --repo newrelic/nri-mssql --output ./bin.zip
          7z x ./bin.zip -o./dist/nri-mssql_windows_amd64/
          tree
      